name: Python CI

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8  

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Debug
      run: |
        pwd
        ls 

    - name: Install dependencies
      run: |
        cd ${{ github.workspace }}
        python -m pip install --upgrade pip
        python demo.py
        python -m pip install -r requirements.txt   

    - name: Update dev branch and run tests
      run: |
        git config --global user.email "roshni.kale@onlinepsbloans.com"
        git config --global user.name "rosh"
        git checkout -b dev
        
        if python -m unittest discover -s ./tests; then
          echo "All tests passed. Committing to dev."
          git add .
          git commit -m "auto-commit: Passed all tests [skip ci]"
          git push origin dev
        else
          echo "Tests failed. Not committing to dev."
        fi
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

